config/routes.rb
Rails.application.routes.draw do

  resources :regions do
    resources :contests do
      resources :stories
    end
  end

  resources :cities
  resources :places

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]

  root 'home#landing'

  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session

    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/contest.rb
class Contest < ActiveRecord::Base

  belongs_to :region
  has_many :stories

  validates :region_id, presence: true

  validates :year, presence:     {is: true},
                   numericality: {is: true},
                   length:       {is: 4  }


  def has_stories?
    stories.any?
  end
  def has_any_register?
    has_stories?
  end

end

app/controllers/contests_controller.rb
class ContestsController < ApplicationController
  before_action :set_contest, only: [:show, :edit, :update, :destroy]

  # GET /contests
  # GET /contests.json
  def index
    @contests = Contest.all
  end

  # GET /contests/1
  # GET /contests/1.json
  def show
  end

  # GET /contests/new
  def new
    @contest = Contest.new
  end

  # GET /contests/1/edit
  def edit
  end

  # POST /contests
  # POST /contests.json
  def create
    @contest = Contest.new(contest_params)

    respond_to do |format|
      if @contest.save
        format.html { redirect_to @contest, notice: 'Contest was successfully created.' }
        format.json { render :show, status: :created, location: @contest }
      else
        format.html { render :new }
        format.json { render json: @contest.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contests/1
  # PATCH/PUT /contests/1.json
  def update
    respond_to do |format|
      if @contest.update(contest_params)
        format.html { redirect_to @contest, notice: 'Contest was successfully updated.' }
        format.json { render :show, status: :ok, location: @contest }
      else
        format.html { render :edit }
        format.json { render json: @contest.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contests/1
  # DELETE /contests/1.json
  def destroy
    @contest.destroy
    respond_to do |format|
      format.html { redirect_to contests_url, notice: 'Contest was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contest
      @contest = Contest.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contest_params
      params.require(:contest).permit(:year, :region_id)
    end
end

app/helpers/contests_helper.rb
module ContestsHelper
end

app/views/contests/_form.html.slim
= simple_form_for(@contest) do |f|
  = f.error_notification

  .form-inputs
    = f.input :year
    = f.association :region

  .form-actions
    = f.button :submit

app/views/contests/edit.html.slim
h1 Editing contest

== render 'form'

= link_to 'Show', @contest
'|
= link_to 'Back', contests_path

app/views/contests/index.html.slim
h1 Listing contests

table.table
  thead
    tr
      th Year
      th Region
      th
      th
      th

  tbody
    - @contests.each do |contest|
      tr
        td = contest.year
        td = contest.region
        td = link_to 'Show', contest
        td = link_to 'Edit', edit_contest_path(contest)
        td = link_to 'Destroy', contest, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Contest', new_contest_path

app/views/contests/new.html.slim
h1 New contest

== render 'form'

= link_to 'Back', contests_path

app/views/contests/show.html.slim
p#notice = notice

p
  strong Year:
  = @contest.year
p
  strong Region:
  = @contest.region

= link_to 'Edit', edit_contest_path(@contest)
'|
= link_to 'Back', contests_path