config/routes.rb
Rails.application.routes.draw do

  resources :regions do
    resources :contests do
      resources :stories
    end
  end

  resources :cities
  resources :places

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]

  root 'home#landing'

  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session

    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/story.rb
class Story < ActiveRecord::Base
  belongs_to :city
  belongs_to :place
  belongs_to :contest

  validates :title,      presence: true
  validates :body,       presence: true
  validates :author,     presence: true
  validates :city_id,    presence: true
  validates :place_id,   presence: true
  validates :contest_id, presence: true

  validates :age, presence:     {is: true},
                  numericality: {is: true},
                  length:       {maximum: 3 }
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_action :set_story, only: [:show, :edit, :update, :destroy]

  # GET /stories
  # GET /stories.json
  def index
    @stories = Story.all
  end

  # GET /stories/1
  # GET /stories/1.json
  def show
  end

  # GET /stories/new
  def new
    @story = Story.new
  end

  # GET /stories/1/edit
  def edit
  end

  # POST /stories
  # POST /stories.json
  def create
    @story = Story.new(story_params)

    respond_to do |format|
      if @story.save
        format.html { redirect_to @story, notice: 'Story was successfully created.' }
        format.json { render :show, status: :created, location: @story }
      else
        format.html { render :new }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stories/1
  # PATCH/PUT /stories/1.json
  def update
    respond_to do |format|
      if @story.update(story_params)
        format.html { redirect_to @story, notice: 'Story was successfully updated.' }
        format.json { render :show, status: :ok, location: @story }
      else
        format.html { render :edit }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stories/1
  # DELETE /stories/1.json
  def destroy
    @story.destroy
    respond_to do |format|
      format.html { redirect_to stories_url, notice: 'Story was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_story
      @story = Story.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def story_params
      params.require(:story).permit(:title, :body, :author, :age, :city_id, :place_id, :contest_id)
    end
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/stories/_form.html.slim
= simple_form_for(@story) do |f|
  = f.error_notification

  .form-inputs
    = f.input :title
    = f.input :body
    = f.input :author
    = f.input :age
    = f.association :city
    = f.association :place
    = f.association :contest

  .form-actions
    = f.button :submit

app/views/stories/edit.html.slim
h1 Editing story

== render 'form'

= link_to 'Show', @story
'|
= link_to 'Back', stories_path

app/views/stories/index.html.slim
h1 Listing stories

table.table
  thead
    tr
      th Title
      th Body
      th Author
      th Age
      th City
      th Place
      th Contest
      th
      th
      th

  tbody
    - @stories.each do |story|
      tr
        td = story.title
        td = story.body
        td = story.author
        td = story.age
        td = story.city
        td = story.place
        td = story.contest
        td = link_to 'Show', story
        td = link_to 'Edit', edit_story_path(story)
        td = link_to 'Destroy', story, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Story', new_story_path

app/views/stories/new.html.slim
h1 New story

== render 'form'

= link_to 'Back', stories_path

app/views/stories/show.html.slim
p#notice = notice

p
  strong Title:
  = @story.title
p
  strong Body:
  = @story.body
p
  strong Author:
  = @story.author
p
  strong Age:
  = @story.age
p
  strong City:
  = @story.city
p
  strong Place:
  = @story.place
p
  strong Contest:
  = @story.contest

= link_to 'Edit', edit_story_path(@story)
'|
= link_to 'Back', stories_path