config/routes.rb
Rails.application.routes.draw do

  resources :regions do
    resources :contests do
      resources :stories
    end
  end

  resources :cities
  resources :places

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]

  root 'home#landing'

  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session

    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/region.rb
class Region < ActiveRecord::Base

  has_many :contest
  has_many :stories, through: :contest

  validates :name, presence: true


  def has_contests?
    contests.any?
  end
  def has_any_register?
    has_contests?
  end

end

app/controllers/regions_controller.rb
class RegionsController < ApplicationController
  before_action :set_region, only: [:show, :edit, :update, :destroy]

  # GET /regions
  # GET /regions.json
  def index
    @regions = Region.all
  end

  # GET /regions/1
  # GET /regions/1.json
  def show
  end

  # GET /regions/new
  def new
    @region = Region.new
  end

  # GET /regions/1/edit
  def edit
  end

  # POST /regions
  # POST /regions.json
  def create
    @region = Region.new(region_params)

    respond_to do |format|
      if @region.save
        format.html { redirect_to @region, notice: 'Region was successfully created.' }
        format.json { render :show, status: :created, location: @region }
      else
        format.html { render :new }
        format.json { render json: @region.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /regions/1
  # PATCH/PUT /regions/1.json
  def update
    respond_to do |format|
      if @region.update(region_params)
        format.html { redirect_to @region, notice: 'Region was successfully updated.' }
        format.json { render :show, status: :ok, location: @region }
      else
        format.html { render :edit }
        format.json { render json: @region.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /regions/1
  # DELETE /regions/1.json
  def destroy
    @region.destroy
    respond_to do |format|
      format.html { redirect_to regions_url, notice: 'Region was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_region
      @region = Region.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def region_params
      params.require(:region).permit(:name)
    end
end

app/helpers/regions_helper.rb
module RegionsHelper
end

app/views/regions/_form.html.slim
= simple_form_for(@region) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name

  .form-actions
    = f.button :submit

app/views/regions/edit.html.slim
h1 Editing region

== render 'form'

= link_to 'Show', @region
'|
= link_to 'Back', regions_path

app/views/regions/index.html.slim
h1 Listing regions

table.table
  thead
    tr
      th Name
      th
      th
      th

  tbody
    - @regions.each do |region|
      tr
        td = region.name
        td = link_to 'Show', region
        td = link_to 'Edit', edit_region_path(region)
        td = link_to 'Destroy', region, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Region', new_region_path

app/views/regions/new.html.slim
h1 New region

== render 'form'

= link_to 'Back', regions_path

app/views/regions/show.html.slim
p#notice = notice

p
  strong Name:
  = @region.name

= link_to 'Edit', edit_region_path(@region)
'|
= link_to 'Back', regions_path