config/routes.rb
Rails.application.routes.draw do

  resources :regions do
    resources :contests do
      resources :stories
    end
  end

  resources :cities
  resources :places

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]

  root 'home#landing'

  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session

    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/place.rb
class Place < ActiveRecord::Base

  has_many :stories

  validates :name, presence: true


  def has_stories?
    stories.any?
  end
  def has_any_register?
    has_stories?
  end

end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :set_place, only: [:show, :edit, :update, :destroy]

  # GET /places
  # GET /places.json
  def index
    @places = Place.all
  end

  # GET /places/1
  # GET /places/1.json
  def show
  end

  # GET /places/new
  def new
    @place = Place.new
  end

  # GET /places/1/edit
  def edit
  end

  # POST /places
  # POST /places.json
  def create
    @place = Place.new(place_params)

    respond_to do |format|
      if @place.save
        format.html { redirect_to @place, notice: 'Place was successfully created.' }
        format.json { render :show, status: :created, location: @place }
      else
        format.html { render :new }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /places/1
  # PATCH/PUT /places/1.json
  def update
    respond_to do |format|
      if @place.update(place_params)
        format.html { redirect_to @place, notice: 'Place was successfully updated.' }
        format.json { render :show, status: :ok, location: @place }
      else
        format.html { render :edit }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /places/1
  # DELETE /places/1.json
  def destroy
    @place.destroy
    respond_to do |format|
      format.html { redirect_to places_url, notice: 'Place was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_place
      @place = Place.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def place_params
      params.require(:place).permit(:name)
    end
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/places/_form.html.slim
= simple_form_for(@place) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name

  .form-actions
    = f.button :submit

app/views/places/edit.html.slim
h1 Editing place

== render 'form'

= link_to 'Show', @place
'|
= link_to 'Back', places_path

app/views/places/index.html.slim
h1 Listing places

table.table
  thead
    tr
      th Name
      th
      th
      th

  tbody
    - @places.each do |place|
      tr
        td = place.name
        td = link_to 'Show', place
        td = link_to 'Edit', edit_place_path(place)
        td = link_to 'Destroy', place, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Place', new_place_path

app/views/places/new.html.slim
h1 New place

== render 'form'

= link_to 'Back', places_path

app/views/places/show.html.slim
p#notice = notice

p
  strong Name:
  = @place.name

= link_to 'Edit', edit_place_path(@place)
'|
= link_to 'Back', places_path